<?php

namespace App\Livewire\Admin\Attendance;

use App\Models\Attendance;
use App\Models\Student;
use App\Models\Semester;
use App\Models\AcademicCalendar;
use Livewire\Component;
use Livewire\Attributes\Layout;
use Livewire\Attributes\Title;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

#[Layout('layouts.admin')]
#[Title('Generate Alpha - Siswa Tidak Absen')]
class GenerateAlpha extends Component
{
    public $selectedDate;
    public $previewData = [];
    public $showPreview = false;
    public $processing = false;

    // Stats
    public $totalWorkingDays = 0;
    public $totalProcessedDays = 0;
    public $totalAlphaGenerated = 0;
    public $lastGeneratedDate = null;
    public $lastGeneratedBy = null;

    public function mount()
    {
        // Set default to yesterday
        $this->selectedDate = Carbon::yesterday()->format('Y-m-d');
        $this->loadStats();
    }

    public function loadStats()
    {
        $activeSemester = Semester::where('is_active', true)->first();

        if ($activeSemester) {
            $startDate = Carbon::parse($activeSemester->start_date);
            $endDate = Carbon::parse($activeSemester->end_date);
            $today = Carbon::today();

            // Count total working days in semester (up to today)
            $this->totalWorkingDays = $this->getWorkingDaysBetween(
                $startDate,
                $endDate->gt($today) ? $today : $endDate
            );

            // Count how many days have been processed
            $processedDates = Attendance::where('status', 'alpha')
                ->where('notes', 'LIKE', '%Auto-generated by system%')
                ->whereBetween('date', [$startDate, $today])
                ->distinct('date')
                ->count('date');

            $this->totalProcessedDays = $processedDates;

            // Count total alpha generated
            $this->totalAlphaGenerated = Attendance::where('status', 'alpha')
                ->where('notes', 'LIKE', '%Auto-generated by system%')
                ->whereBetween('date', [$startDate, $today])
                ->count();

            // Get last generation info
            $lastGenerated = Attendance::where('status', 'alpha')
                ->where('notes', 'LIKE', '%Auto-generated by system%')
                ->orderBy('created_at', 'desc')
                ->first();

            if ($lastGenerated) {
                $this->lastGeneratedDate = $lastGenerated->created_at->format('d/m/Y H:i');
                // Extract user from notes
                if (preg_match('/by (.+?) at/', $lastGenerated->notes, $matches)) {
                    $this->lastGeneratedBy = $matches[1];
                }
            }
        }
    }

    public function preview()
    {
        $this->validate([
            'selectedDate' => 'required|date|before_or_equal:today',
        ], [
            'selectedDate.required' => 'Tanggal harus diisi',
            'selectedDate.date' => 'Format tanggal tidak valid',
            'selectedDate.before_or_equal' => 'Tidak bisa generate untuk tanggal yang akan datang',
        ]);

        $date = Carbon::parse($this->selectedDate);

        // Check if it's a working day
        if ($date->isWeekend()) {
            session()->flash('error', 'Tanggal yang dipilih adalah hari weekend. Pilih hari kerja (Senin-Jumat).');
            return;
        }

        // Check if it's a holiday
        if (AcademicCalendar::isHoliday($date)) {
            session()->flash('error', 'Tanggal yang dipilih adalah hari libur berdasarkan kalender akademik.');
            return;
        }

        // Check if in active semester
        $activeSemester = Semester::where('is_active', true)->first();
        if (!$activeSemester) {
            session()->flash('error', 'Tidak ada semester aktif. Aktifkan semester terlebih dahulu.');
            return;
        }

        $semesterStart = Carbon::parse($activeSemester->start_date);
        $semesterEnd = Carbon::parse($activeSemester->end_date);

        if ($date->lt($semesterStart) || $date->gt($semesterEnd)) {
            session()->flash('error', 'Tanggal yang dipilih berada di luar periode semester aktif (' . $semesterStart->format('d/m/Y') . ' - ' . $semesterEnd->format('d/m/Y') . ').');
            return;
        }

        // Get all active students
        $activeStudents = Student::where('is_active', true)
            ->with(['class.department'])
            ->get();

        // Get students who already have attendance on this date
        $studentsWithAttendance = Attendance::whereDate('date', $date)
            ->pluck('student_id')
            ->toArray();

        // Find students without attendance
        $studentsWithoutAttendance = $activeStudents->filter(function ($student) use ($studentsWithAttendance) {
            return !in_array($student->id, $studentsWithAttendance);
        });

        // Count students who checked in but didn't check out
        $studentsWithoutCheckout = Attendance::whereDate('date', $date)
            ->whereNotNull('check_in_time')
            ->whereNull('check_out_time')
            ->where('status', '!=', 'tidak_checkout')
            ->count();

        $this->previewData = [
            'date' => $date->format('d/m/Y'),
            'dateCarbon' => $date,
            'total_active_students' => $activeStudents->count(),
            'students_with_attendance' => count($studentsWithAttendance),
            'students_without_attendance' => $studentsWithoutAttendance->count(),
            'students_without_checkout' => $studentsWithoutCheckout,
            'students_list' => $studentsWithoutAttendance->take(10), // Show first 10 for preview
            'total_to_show' => $studentsWithoutAttendance->count() > 10 ? 10 : $studentsWithoutAttendance->count(),
        ];

        $this->showPreview = true;
    }

    public function generate()
    {
        if (!$this->showPreview || empty($this->previewData)) {
            session()->flash('error', 'Silakan preview terlebih dahulu sebelum generate.');
            return;
        }

        $this->processing = true;

        try {
            DB::beginTransaction();

            $date = $this->previewData['dateCarbon'];
            $activeSemester = Semester::where('is_active', true)->first();

            // Get all active students
            $activeStudents = Student::where('is_active', true)->get();

            // Get students who already have attendance
            $studentsWithAttendance = Attendance::whereDate('date', $date)
                ->pluck('student_id')
                ->toArray();

            $generated = 0;

            foreach ($activeStudents as $student) {
                // Skip if student already has attendance
                if (in_array($student->id, $studentsWithAttendance)) {
                    continue;
                }

                // Create alpha attendance record
                Attendance::create([
                    'student_id' => $student->id,
                    'class_id' => $student->class_id,
                    'semester_id' => $activeSemester->id,
                    'date' => $date,
                    'check_in_time' => null,
                    'check_out_time' => null,
                    'status' => 'alpha',
                    'percentage' => 0,
                    'late_minutes' => 0,
                    'early_leave_minutes' => 0,
                    'check_in_method' => 'system',
                    'notes' => 'Auto-generated by system - Student absent without permission. Generated by ' . auth()->user()->name . ' at ' . now()->format('d/m/Y H:i:s'),
                ]);

                $generated++;
            }

            // Update status for students who checked in but didn't check out
            $updated = Attendance::whereDate('date', $date)
                ->whereNotNull('check_in_time')
                ->whereNull('check_out_time')
                ->where('status', '!=', 'tidak_checkout')
                ->update([
                    'status' => 'tidak_checkout',
                    'percentage' => 50,
                    'notes' => DB::raw("CONCAT(COALESCE(notes, ''), ' | Status updated to tidak_checkout by system. Updated by " . auth()->user()->name . " at " . now()->format('d/m/Y H:i:s') . "')")
                ]);

            // Log the action
            Log::info('Alpha generation completed', [
                'date' => $date->format('Y-m-d'),
                'generated_count' => $generated,
                'updated_tidak_checkout' => $updated,
                'user' => auth()->user()->name,
                'user_id' => auth()->id(),
            ]);

            DB::commit();

            $message = "Berhasil generate {$generated} record alpha untuk tanggal {$date->format('d/m/Y')}.";
            if ($updated > 0) {
                $message .= " {$updated} siswa yang check-in tapi tidak check-out telah diupdate statusnya menjadi 'tidak checkout'.";
            }
            session()->flash('success', $message);

            $this->showPreview = false;
            $this->previewData = [];
            $this->loadStats();

        } catch (\Exception $e) {
            DB::rollBack();
            Log::error('Alpha generation failed', [
                'error' => $e->getMessage(),
                'trace' => $e->getTraceAsString(),
            ]);
            session()->flash('error', 'Gagal generate alpha: ' . $e->getMessage());
        }

        $this->processing = false;
    }

    public function cancelGeneration($date)
    {
        try {
            DB::beginTransaction();

            $targetDate = Carbon::parse($date);

            // Delete only auto-generated alpha records for this date
            $deleted = Attendance::whereDate('date', $targetDate)
                ->where('status', 'alpha')
                ->where('notes', 'LIKE', '%Auto-generated by system%')
                ->delete();

            // Log the cancellation
            Log::info('Alpha generation cancelled', [
                'date' => $targetDate->format('Y-m-d'),
                'deleted_count' => $deleted,
                'user' => auth()->user()->name,
                'user_id' => auth()->id(),
            ]);

            DB::commit();

            session()->flash('success', "Berhasil membatalkan {$deleted} record alpha untuk tanggal {$targetDate->format('d/m/Y')}.");

            $this->loadStats();

        } catch (\Exception $e) {
            DB::rollBack();
            Log::error('Alpha cancellation failed', [
                'error' => $e->getMessage(),
                'trace' => $e->getTraceAsString(),
            ]);
            session()->flash('error', 'Gagal membatalkan: ' . $e->getMessage());
        }
    }

    public function generateBulk()
    {
        $this->processing = true;

        try {
            DB::beginTransaction();

            $activeSemester = Semester::where('is_active', true)->first();

            if (!$activeSemester) {
                session()->flash('error', 'Tidak ada semester aktif.');
                return;
            }

            $startDate = Carbon::parse($activeSemester->start_date);
            $endDate = Carbon::parse($activeSemester->end_date);
            $today = Carbon::today();

            // Only process up to yesterday
            $yesterday = Carbon::yesterday();
            if ($endDate->gt($yesterday)) {
                $endDate = $yesterday;
            }

            $totalGenerated = 0;
            $totalUpdated = 0;
            $daysProcessed = 0;

            $current = $startDate->copy();
            while ($current->lte($endDate)) {
                // Only process weekdays
                if ($current->isWeekday() && !AcademicCalendar::isHoliday($current)) {
                    // Get all active students
                    $activeStudents = Student::where('is_active', true)->get();

                    // Get students who already have attendance
                    $studentsWithAttendance = Attendance::whereDate('date', $current)
                        ->pluck('student_id')
                        ->toArray();

                    foreach ($activeStudents as $student) {
                        // Skip if student already has attendance
                        if (in_array($student->id, $studentsWithAttendance)) {
                            continue;
                        }

                        // Create alpha attendance record
                        Attendance::create([
                            'student_id' => $student->id,
                            'class_id' => $student->class_id,
                            'semester_id' => $activeSemester->id,
                            'date' => $current,
                            'check_in_time' => null,
                            'check_out_time' => null,
                            'status' => 'alpha',
                            'percentage' => 0,
                            'late_minutes' => 0,
                            'early_leave_minutes' => 0,
                            'check_in_method' => 'system',
                            'notes' => 'Auto-generated by system - Bulk generation. Generated by ' . auth()->user()->name . ' at ' . now()->format('d/m/Y H:i:s'),
                        ]);

                        $totalGenerated++;
                    }

                    // Update status for students who checked in but didn't check out
                    $updated = Attendance::whereDate('date', $current)
                        ->whereNotNull('check_in_time')
                        ->whereNull('check_out_time')
                        ->where('status', '!=', 'tidak_checkout')
                        ->update([
                            'status' => 'tidak_checkout',
                            'percentage' => 50,
                            'notes' => DB::raw("CONCAT(COALESCE(notes, ''), ' | Status updated to tidak_checkout by system. Updated by " . auth()->user()->name . " at " . now()->format('d/m/Y H:i:s') . "')")
                        ]);

                    $totalUpdated += $updated;
                    $daysProcessed++;
                }

                $current->addDay();
            }

            // Log the action
            Log::info('Bulk alpha generation completed', [
                'start_date' => $startDate->format('Y-m-d'),
                'end_date' => $endDate->format('Y-m-d'),
                'days_processed' => $daysProcessed,
                'generated_count' => $totalGenerated,
                'updated_tidak_checkout' => $totalUpdated,
                'user' => auth()->user()->name,
                'user_id' => auth()->id(),
            ]);

            DB::commit();

            $message = "Berhasil generate {$totalGenerated} record alpha untuk {$daysProcessed} hari kerja.";
            if ($totalUpdated > 0) {
                $message .= " {$totalUpdated} siswa yang check-in tapi tidak check-out telah diupdate statusnya menjadi 'tidak checkout'.";
            }
            session()->flash('success', $message);

            $this->loadStats();

        } catch (\Exception $e) {
            DB::rollBack();
            Log::error('Bulk alpha generation failed', [
                'error' => $e->getMessage(),
                'trace' => $e->getTraceAsString(),
            ]);
            session()->flash('error', 'Gagal generate bulk alpha: ' . $e->getMessage());
        }

        $this->processing = false;
    }

    private function getWorkingDaysBetween($startDate, $endDate)
    {
        $start = Carbon::parse($startDate);
        $end = Carbon::parse($endDate);
        $workingDays = 0;

        $holidayDates = AcademicCalendar::getHolidayDates($start, $end);

        while ($start <= $end) {
            if ($start->isWeekday() && !in_array($start->format('Y-m-d'), $holidayDates)) {
                $workingDays++;
            }
            $start->addDay();
        }

        return $workingDays;
    }

    public function render()
    {
        return view('livewire.admin.attendance.generate-alpha');
    }
}
