-- Create activity_logs table
CREATE TABLE IF NOT EXISTS `activity_logs` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) unsigned DEFAULT NULL COMMENT 'User yang melakukan aksi',
  `action` varchar(100) NOT NULL COMMENT 'Jenis aksi: login, logout, create, update, delete, view, export, etc',
  `description` varchar(255) NOT NULL COMMENT 'Deskripsi aktivitas',
  `subject_type` varchar(100) DEFAULT NULL COMMENT 'Model yang diubah (User, Student, Attendance, etc)',
  `subject_id` bigint(20) unsigned DEFAULT NULL COMMENT 'ID record yang diubah',
  `ip_address` varchar(45) DEFAULT NULL COMMENT 'IP address pengguna',
  `user_agent` varchar(255) DEFAULT NULL COMMENT 'Browser/device info',
  `method` varchar(10) DEFAULT NULL COMMENT 'HTTP method: GET, POST, PUT, DELETE',
  `url` varchar(255) DEFAULT NULL COMMENT 'URL endpoint',
  `properties` json DEFAULT NULL COMMENT 'Data before/after changes',
  `request_data` json DEFAULT NULL COMMENT 'Request payload (sensitive data filtered)',
  `category` enum('authentication','user_management','student_management','attendance','approval','settings','report','system') NOT NULL DEFAULT 'system' COMMENT 'Kategori aktivitas',
  `severity` enum('info','warning','critical') NOT NULL DEFAULT 'info' COMMENT 'Tingkat kepentingan',
  `session_id` varchar(255) DEFAULT NULL COMMENT 'Session ID',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `activity_logs_user_id_index` (`user_id`),
  KEY `activity_logs_action_index` (`action`),
  KEY `activity_logs_category_index` (`category`),
  KEY `activity_logs_severity_index` (`severity`),
  KEY `activity_logs_subject_type_subject_id_index` (`subject_type`,`subject_id`),
  KEY `activity_logs_created_at_index` (`created_at`),
  KEY `activity_logs_ip_address_index` (`ip_address`),
  CONSTRAINT `activity_logs_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
