<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var list<string>
     */
    protected $fillable = [
        'role_id',
        'name',
        'email',
        'password',
        'phone',
        'photo',
        'is_active',
        'last_login_at',
        'last_login_ip',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var list<string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'email_verified_at' => 'datetime',
            'password' => 'hashed',
            'is_active' => 'boolean',
            'last_login_at' => 'datetime',
            'created_at' => 'datetime',
            'updated_at' => 'datetime',
            'deleted_at' => 'datetime',
        ];
    }

    /**
     * Get the role this user belongs to
     */
    public function role()
    {
        return $this->belongsTo(Role::class);
    }

    /**
     * Get the student profile (if user is a student)
     */
    public function student()
    {
        return $this->hasOne(Student::class);
    }

    /**
     * Get classes where this user is wali kelas
     */
    public function classesAsWaliKelas()
    {
        return $this->hasMany(Classes::class, 'wali_kelas_id');
    }

    /**
     * Get notifications for this user
     */
    public function notifications()
    {
        return $this->hasMany(Notification::class);
    }

    /**
     * Get unread notifications
     */
    public function unreadNotifications()
    {
        return $this->notifications()->unread();
    }

    /**
     * Get audit logs for this user
     */
    public function auditLogs()
    {
        return $this->hasMany(AuditLog::class);
    }

    /**
     * Get manual attendances requested by this user
     */
    public function requestedManualAttendances()
    {
        return $this->hasMany(ManualAttendance::class, 'requested_by');
    }

    /**
     * Get manual attendances approved by this user
     */
    public function approvedManualAttendances()
    {
        return $this->hasMany(ManualAttendance::class, 'approved_by');
    }

    /**
     * Get attendance approvals requested by this user
     */
    public function requestedApprovals()
    {
        return $this->hasMany(AttendanceApproval::class, 'requested_by');
    }

    /**
     * Get attendance approvals handled by this user
     */
    public function handledApprovals()
    {
        return $this->hasMany(AttendanceApproval::class, 'approved_by');
    }

    /**
     * Get reports generated by this user
     */
    public function generatedReports()
    {
        return $this->hasMany(AttendanceReport::class, 'generated_by');
    }

    /**
     * Check if user has specific role
     */
    public function hasRole(string $roleName): bool
    {
        return $this->role && $this->role->name === $roleName;
    }

    /**
     * Check if user has any of the given roles
     */
    public function hasAnyRole(array $roles): bool
    {
        return $this->role && in_array($this->role->name, $roles);
    }

    /**
     * Check if user has specific permission
     */
    public function hasPermission(string $permissionName): bool
    {
        return $this->role && $this->role->hasPermission($permissionName);
    }

    /**
     * Check if user has any of the given permissions
     */
    public function hasAnyPermission(array $permissions): bool
    {
        return $this->role && $this->role->hasAnyPermission($permissions);
    }

    /**
     * Check if user is admin
     */
    public function isAdmin(): bool
    {
        return $this->hasRole('admin');
    }

    /**
     * Check if user is kepala sekolah
     */
    public function isKepalaSekolah(): bool
    {
        return $this->hasRole('kepala_sekolah');
    }

    /**
     * Check if user is wali kelas
     */
    public function isWaliKelas(): bool
    {
        return $this->hasRole('wali_kelas');
    }

    /**
     * Check if user is student
     */
    public function isStudent(): bool
    {
        return $this->hasRole('siswa');
    }

    /**
     * Update last login info
     */
    public function updateLastLogin(?string $ipAddress = null): bool
    {
        $this->last_login_at = now();
        $this->last_login_ip = $ipAddress ?? request()->ip();

        return $this->save();
    }

    /**
     * Scope: only active users
     */
    public function scopeActive($query)
    {
        return $query->where('is_active', true);
    }

    /**
     * Scope: filter by role
     */
    public function scopeByRole($query, string $roleName)
    {
        return $query->whereHas('role', function ($q) use ($roleName) {
            $q->where('name', $roleName);
        });
    }

    /**
     * Scope: only admins
     */
    public function scopeAdmins($query)
    {
        return $query->byRole('admin');
    }

    /**
     * Scope: only wali kelas
     */
    public function scopeWaliKelas($query)
    {
        return $query->byRole('wali_kelas');
    }

    /**
     * Scope: only students
     */
    public function scopeStudents($query)
    {
        return $query->byRole('siswa');
    }
}
